version: "3"

networks:
  default:
    external:
      name: ehh-world-dev-network

services:
  ehhioserver:
    container_name: ehhioserver
    build:
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ~\.ssh\id_rsa:/root/.ssh/id_rsa
      #- .:/go/src/app

  database:
      image: postgres:latest
      container_name: postgres
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: ehhworlddb
      volumes:
        - ../server/db/sql/init/:/docker-entrypoint-initdb.d/

