version: "3"

networks:
  default:
    external:
      name: ehh-world-dev-network

services:
  ehhio_server:
    container_name: ehhio_server
    build:
      context: ..
      dockerfile: ./Dockerfile
      args:
        repo_private_key: ${REPO_PRIVATE_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
      image: postgres:latest
      restart: always
      ports:
        - 5432:5432
      environment:
        POSTGRES_PASSWORD: ehhworlddb
      volumes:
        - ../server/db/sql/init/:/docker-entrypoint-initdb.d/

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - postgres
    environment:
      SLEEP_LENGTH: 2.0
    command: postgres:5432
