// Code generated by "stringer -type=Biome"; DO NOT EDIT.

package gamemap

import "fmt"

const _Biome_name = "SaltwaterDeepSaltwaterShallowFreshwaterDeepFreshwaterShallowShoreSubtropicalDesertGrasslandTropicalSeasonalForestTropicalRainForestTemperateDesertTemperateDeciduousForestTemperateRainForestShrublandTaigaScorchedBareTundraSnow"

var _Biome_index = [...]uint8{0, 13, 29, 43, 60, 65, 82, 91, 113, 131, 146, 170, 189, 198, 203, 211, 215, 221, 225}

func (i Biome) String() string {
	if i < 0 || i >= Biome(len(_Biome_index)-1) {
		return fmt.Sprintf("Biome(%d)", i)
	}
	return _Biome_name[_Biome_index[i]:_Biome_index[i+1]]
}
