// Code generated by "stringer -type=CellShape"; DO NOT EDIT.

package gamemap

import "fmt"

const _CellShape_name = "FullTopHalfBottomHalfLeftHalfRightHalfTopLeftQuarterTopRightQuarterBottomLeftQuarterBottomRightQuarter"

var _CellShape_index = [...]uint8{0, 4, 11, 21, 29, 38, 52, 67, 84, 102}

func (i CellShape) String() string {
	if i < 0 || i >= CellShape(len(_CellShape_index)-1) {
		return fmt.Sprintf("CellShape(%d)", i)
	}
	return _CellShape_name[_CellShape_index[i]:_CellShape_index[i+1]]
}
